# Generated by Django 4.1.1 on 2022-09-11 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('profile_img', models.TextField()),
                ('registered_diecasts', models.IntegerField(default=0)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
